services:
  - type: web
    name: lobi-backend
    runtime: python
    plan: free
    buildCommand: "bash build.sh"
    startCommand: "python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
